# Generated by Django 2.0 on 2018-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandV7',
            fields=[
                ('bno', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('brand_name', models.CharField(max_length=200)),
                ('eng_name', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
    ]
